name: open_mensa_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.0+1

  tuple: ^1.0.2
  sqflite: ^1.1.0
  path: ^1.6.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.6

  flutter_launcher_icons: ^0.7.0
  equatable: ^1.1.0
  rxdart: ^0.23.0
  path_provider: ^1.5.1
  flutter_bloc: ^3.2.0
  hive_flutter: ^0.2.1
  build_runner: ^1.7.1
  hive_generator: ^0.5.2
  groovin_material_icons: ^1.1.6

flutter_icons:
  image_path: "icon/dish.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/bacon.png
    - images/broccoli.png
    - images/burger.png
    - images/cauliflower.png
    - images/chili.png
    - images/choco.png
    - images/cow.png
    - images/dumpling.png
    - images/earth.jpg
    - images/egg.png
    - images/fish.png
    - images/forkSpoon.png
    - images/haehnchenBrust.png
    - images/ingredients.jpg
    - images/pralines.jpg
    - images/lasagne.png
    - images/map.png
    - images/ingredientsRound.jpg
    - images/omlett.png
    - images/pizza.png
    - images/pommes.png
    - images/pork.png
    - images/ravioli.png
    - images/roesti.png
    - images/sad.png
    - images/salat.png
    - images/sausage.png
    - images/schnitzel.png
    - images/sheep.png
    - images/spaghetti.png
    - images/unknownDish.png
    - images/vanille.png
    - images/yoghurt.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
